---
language:
- node_js
node_js:
- "14"
install:
- npm install purescript -g
- npm install -q --no-color --no-progress
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
script:
- npx nyc --reporter=lcov npx mocha --recursive './test/**/*.js' --require @babel/register --require esm
after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
---
